### ISSUE TITLE
Is FDK-AAC preferred over FAAD2?

### ISSUE THREAD

**Issue by russel** [Opendigitalradio/dablin#11]
The README explains about FAAD2, FDK-AAC, and an amended version of the latter, but no ordering/preference is offered. Should a preference be made explicit?

**Comment by basicmaster** [comment]
Currently there is an implicit preference for FAAD2 as it belongs to the required libs, while only a subsection explains the usage of the FDK-AAC alternative.

I added FDK-AAC just for the sake of completeness in terms of AAC decoders. Sometime maybe I will extend the code to allow using the commercial FDK-AAC version which supports decoding MPEG Surround.

Apart from that I'm not aware of any big differences between the two libs and therefore would like to stick to the current implicit preference.

**Comment by russel** [comment]
OK, that works for me.
