### ISSUE TITLE
Possible new GUI

### ISSUE THREAD

**Issue by russel** [Opendigitalradio/dablin#13]
Users of the DABlin GUI probably do not really care about channels and ensembles, that is unwanted detail, they just want a list of the receivable services (aka radio stations ­– should services be renamed station in the en_GB version). Most commercial DAB/DAB+ radios spend a little time finding all the currently available stations before actually playing anything. It is not clear what the commercial DAB/DAB+ devices do here. I assume they scan all the Band III channels for signal and then for those with signal await the station list.

I propose a new (possibly additional, possibly replacement, more likely additional) GUI that first scans, and then just displays receivable radio stations.

**Comment by basicmaster** [comment]
In general I agree with you that channels/ensembles should not be important for users. But the problem currently is that the dabtools are not as reliable as desired and sometimes crash on switching (switching currently means: killing `dab2eti` and restarting) the channel. Furthermore many users have not the recommended E4000 tuner with autogain (where locking takes e.g. 5-10s) but other tuners which take e.g. half a minute to lock or longer - and furthermore require that a matching gain has been set by hand. So the user experience in general is unfortunately not yet ready for average Joe but rather for people who e.g. know what a DAB ensemble is.

Thus currently it is much more attractive to just switch to a service on the same ensemble which takes ~300ms. The term "service" btw comes from the DAB spec; "station" may indeed be more appropriate here.

I'm of course open for a new GUI; currently it then should be an additional one.

**Comment by russel** [comment]
I am finding that even with an E4000 you cannot rely on autogain, but must set a gain explicitly. It is not clear to me currently how best to "guess" the gain to get things to work reliably. I suspect that the aerials that come with the USB devices are worse that useless, and that aerials for DVB aren't reliable for DAB. The commercial DAB receivers I have all just seem to have a thin wire as aerial. Your point about the device behaviour affecting user expectation is a good one, so yes any station search is really for the future. Making dab2eti more reliable is clearly an issue. I see that the ENSEMBLES directory in the DABtools repository has the beginnings of files analogous to the DVB channel files, but more as notes than a machine readable form.

**Comment by basicmaster** [comment]
I myself don't experience problems with the E4000 autogain so far. Maybe this has something to do with the fact that the stick is connected to a roof antenna lieing on the floor :-) The DAB reception is much better with an AirSpy, used with SDR-J.

**Comment by russel** [comment]
I'll see about getting an AirSpy, the problem is aerials. I am sure DABlin can beat SDR-J.

**Comment by basicmaster** [comment]
As there has been no progress here, I close this for now. Please feel free to re-open on any news.
