### ISSUE TITLE
Two questions about the Travis-CI build.

### ISSUE THREAD

**Issue by russel** [Opendigitalradio/dablin#14]
1. Should the distribution used be changed to xenial?

2. Should libfdk-aac be tested as well as libfaad2?

**Comment by kylegordon** [comment]
At least for question 1... Yes, I find it preferable to track up to date LTS distros, and then retain support for older ones in edge cases where need be.

**Comment by russel** [comment]
I'll do a pull request to get the distribution updated and to run the two builds one for libfaad2 and one for libfdk-aac since the latter is in Xenial (it was in Trusty as well it seems).
