### ISSUE TITLE
Update .travis.yml

### ISSUE THREAD

**Issue by russel** [Opendigitalradio/dablin#18]
The Travis-CI folk tell me Xenial is not supported yet, we might as well alter the .travis.yml file to the following. I am not sure how to create a pull request for this as I have an outstanding pull request on my GitHub clone.

```
language: c++
sudo: required
dist: trusty

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y libfaad-dev libfdk-aac-dev libmpg123-dev libsdl2-dev libgtkmm-3.0-dev

script:
  - |
    pushd /tmp
    git clone https://github.com/Opendigitalradio/ka9q-fec.git
    cd ka9q-fec
    mkdir build
    cd build
    cmake ..
    make
    sudo make install
    popd
  - |
    mkdir build_faad
    pushd build_faad
    cmake ..
    make
    popd
    mkdir build_fdkaac
    pushd build_fdkaac
    cmake -DUSE_FDK-AAC=1 ..
    make
    popd
```

**Comment by basicmaster** [comment]
Hmm, indeed `xenial` is not supported. This is strange; I would have expected that Travis aborts when `dist` has an unsupported value.

You can just create a new branch (e.g. `features_travis_fix`), based on the last commit that is not contained in the other PR. After commiting and pushing the change to your DABlin fork, you can create a new PR for that branch.

**Comment by russel** [comment]
Me not thinking well enough. My excuse is that I have a cold and it is affecting thought waves. In truth I should have used a branch to the other pull request in the first place. I will fix this.

The Travis-CI people were all apologetic about not failing with an illegal dist, but when they stated a fallback that wasn't actually the case, I began to wonder about the knowledge level of the Travis-CI support folk. I am raising a bug on Travis-CI about this. More new later.

**Comment by russel** [comment]
Now turned into pull request https://github.com/Opendigitalradio/dablin/pull/19

**Comment by basicmaster** [comment]
Oh, so get well soon! I close this issue for the moment as I don't expect that Travis will support Xenial so soon, according to some posts of employees in other issues on GitHub.
