### ISSUE TITLE
Dropouts from stdin?

### ISSUE THREAD

**Issue by andimik** [Opendigitalradio/dablin#21]
See https://github.com/JvanKatwijk/qt-dab/issues/22

`./eti-frontend -O - | dablin_gtk`

> SDLOutput: silence started...
> SDLOutput: silence ended (115200 bytes)
> SDLOutput: silence started...
> SDLOutput: silence ended (117760 bytes)
> SDLOutput: silence started...
> SDLOutput: silence ended (199680 bytes)
> SDLOutput: silence started...
> SDLOutput: silence ended (101376 bytes)
> SDLOutput: silence started...

I don't know yet, if the problem comes from eti-stuff or dablin produces these dropouts.

**Comment by andimik** [comment]
It was a prerecorded file (I tried raw and sdr) 

Will drive to a place where the signal is good enough for Airspy.

**Comment by basicmaster** [comment]
Have you had the chance to check this in the meantime?

**Comment by andimik** [comment]
Seems listening live through an Airspy is not affected. I don't have stable DAB+ reception at home, so I had to drive 30 min.

Then I thought that only *.sdr files don't work, but then also the raw-file mentioned on https://github.com/AlbrechtL/welle.io/issues/30#issuecomment-288872557

The first second is ok, but then these messages "silence started - ended" appear, in DAB as well as DAB+.

My syntax is `eti-frontend -O - | dablin_gtk` and I load this raw file to eti-frontend, waiting for 2 seconds and then press `eti waiting`.

My problem is I don't know where these dropouts are coming from (your or Jan's program).

**Comment by basicmaster** [comment]
Hmm, the mentioned raw file works quite well here. Do you get errors like `(5+)` or `(AU #2)`, before the silence start/end messages? If not, could you post a complete log (e.g. upload to pastebin)?

**Comment by andimik** [comment]
Ok good to know

I'll check my installation

**Comment by andimik** [comment]
Yes, I see 5+

```
andreas@andiE535:~$ /home/andreas/eti-stuff/linux-bin/eti-frontend -O - | dablin_gtk 
DABlin v1.3.0 - capital DAB experience
Plays a DAB/DAB+ audio service from a frame-aligned ETI-NI stream.
  https://github.com/Opendigitalradio/dablin

SDLOutput: using SDL version '2.0.4'
ETISource: reading from 'stdin'
ofdmProcessor is closing down
ofdmProcessor is closing down

(eti-frontend:6971): Gtk-WARNING **: Invalid input string

(eti-frontend:6971): Gtk-WARNING **: Invalid input string
Period = 16000
Starting 1

FICDecoder: found new audio service: SId 0x9202, subchannel  1, DAB+
FICDecoder: found new audio service: SId 0x9203, subchannel  3, DAB+
FICDecoder: found new audio service: SId 0x9201, subchannel  0, DAB+
FICDecoder: found new audio service: SId 0x9436, subchannel 12, DAB+
FICDecoder: found new audio service: SId 0x9462, subchannel 15, DAB+
FICDecoder: found new audio service: SId 0x9516, subchannel 11, DAB+
FICDecoder: found new audio service: SId 0x945B, subchannel 10, DAB+
FICDecoder: found new audio service: SId 0x9459, subchannel  9, DAB+
FICDecoder: found new audio service: SId 0x940B, subchannel  8, DAB+
FICDecoder: found new audio service: SId 0x9442, subchannel  7, DAB+
FICDecoder: found new audio service: SId 0x9414, subchannel  5, DAB+
FICDecoder: found new audio service: SId 0x942F, subchannel  4, DAB+
FICDecoder: found new audio service: SId 0x933A, subchannel  2, DAB+
FICDecoder: found new ensemble label: EId 0x9200, 'MULTIPLEX R1'
FICDecoder: found new programme service label: SId 0x9201, 'Slo 1 Prvi'
FICDecoder: found new programme service label: SId 0x9203, 'Slo 3 ARS'
FICDecoder: found new programme service label: SId 0x9202, 'Slo 2 Val 202'
FICDecoder: found new programme service label: SId 0x933A, 'Slo Int Radio SI'
FICDecoder: found new programme service label: SId 0x942F, 'Radio Ognjisce'
FICDecoder: found new programme service label: SId 0x9414, 'Radio Center Slo'
FICDecoder: found new programme service label: SId 0x9442, 'Radio 1 DAB'
FICDecoder: found new programme service label: SId 0x940B, 'Radio Antena'
FICDecoder: found new programme service label: SId 0x9459, 'Radio 2'
ETIPlayer: playing subchannel 0 (DAB+)
FICDecoder: found new programme service label: SId 0x945B, 'Radio BOB'
FICDecoder: found new programme service label: SId 0x9516, 'Rock Radio Slo'
FICDecoder: found new programme service label: SId 0x9462, 'Glasbeni Radio'
FICDecoder: found new programme service label: SId 0x9436, 'A-Radio'
(0+) SuperframeFilter: Superframe sync started...
(0+) SuperframeFilter: Superframe sync succeeded after 2 frame(s)
ETIPlayer: format: AAC-LC, 48 kHz Stereo @ 128 kBit/s
AACDecoder: using decoder 'FAAD2'
SDLOutput: using audio buffer of 192000 bytes
SDLOutput: audio opened; driver name: pulseaudio, freq: 48000, channels: 2, size: 16384, samples: 2048, silence: 0x00, output: 32bit float
ETIPlayer: playing subchannel 2 (DAB+)
SDLOutput: silence started...
(5+) SuperframeFilter: Superframe sync started...
(0+) (0+) (0+) SuperframeFilter: Superframe sync succeeded after 4 frame(s)
ETIPlayer: format: AAC-LC, 48 kHz Stereo @ 128 kBit/s
AACDecoder: using decoder 'FAAD2'
SDLOutput: silence ended (279040 bytes)
SDLOutput: silence started...
SDLOutput: silence ended (33280 bytes)
SDLOutput: silence started...
SDLOutput: silence ended (183296 bytes)
SDLOutput: silence started...
SDLOutput: silence ended (117760 bytes)
SDLOutput: silence started...
SDLOutput: silence ended (199680 bytes)
SDLOutput: silence started...
SDLOutput: silence ended (101376 bytes)
SDLOutput: silence started...
SDLOutput: silence ended (199680 bytes)
SDLOutput: silence started...
SDLOutput: silence ended (117760 bytes)
SDLOutput: silence started...
SDLOutput: silence ended (199680 bytes)
SDLOutput: silence started...
SDLOutput: silence ended (101376 bytes)
SDLOutput: silence started...
SDLOutput: silence ended (199680 bytes)
SDLOutput: silence started...
SDLOutput: silence ended (101376 bytes)
SDLOutput: silence started...
SDLOutput: silence ended (199680 bytes)
SDLOutput: silence started...
SDLOutput: silence ended (117760 bytes)
SDLOutput: silence started...
SDLOutput: silence ended (183296 bytes)
SDLOutput: silence started...
SDLOutput: silence ended (117760 bytes)
SDLOutput: silence started...
SDLOutput: silence ended (199680 bytes)
SDLOutput: silence started...
SDLOutput: silence ended (101376 bytes)
SDLOutput: silence started...

```

**Comment by basicmaster** [comment]
The silence messages (and hence silenced audio) should only occur after errors happened or some seconds after switching to a service. The reason is an audio buffer underrun.

When this happens with DAB+ services, e.g. `(5+)` (the `+` is important, as it means that there were errors that could not be corrected by the Reed Solomon coding) or `(AU #2)` shows that.

DAB services have a CRC as well, but as the used mpg123 lib does not implement the CRC and it is quite complicated, it is not checked. Hence there is no message when the audio decoder does not output frames.

The silence should only occur in the mentioned cases. Does it also occur in other cases?

**Comment by andimik** [comment]
I found out an older version of eti-stuff from 29th Jan 2017 does not have these dropouts (only after EOF and restarting)

So I close this issue as I found the root cause ...

**Comment by aleena57** [comment]
I could generate DAB file but am unable to generate DAB+ file. While playing the audio through dablin_gtk, audio is not clear.
SDLOutput: silence started...
SDLOutput: silence ended (115200 bytes)
SDLOutput: silence started...
SDLOutput: silence ended (117760 bytes)
SDLOutput: silence started...
SDLOutput: silence ended (199680 bytes)
SDLOutput: silence started...
SDLOutput: silence ended (101376 bytes)
SDLOutput: silence started...

getting errors like (5+) or (AU #2), before the silence start/end messages

**Comment by aleena57** [comment]
I could generate DAB file but am unable to generate DAB+ file. While playing the audio through dablin_gtk, audio is not clear.

SDLOutput: silence started...
(0+) (AU #2) SDLOutput: silence ended (15360 bytes)
SDLOutput: silence started...
(0+) (AU #2) SDLOutput: silence ended (15360 bytes)
SDLOutput: silence started...
(0+) (AU #2) SDLOutput: silence ended (15360 bytes)
SDLOutput: silence started...
(0+) (AU #2) SDLOutput: silence ended (6144 bytes)
SDLOutput: silence started...
(0+) (AU #2) SDLOutput: silence ended (15360 bytes)
SDLOutput: silence started...
(0+) (AU #2) SDLOutput: silence ended (15360 bytes)
SDLOutput: silence started...
(0+) (AU #2) SDLOutput: silence ended (24576 bytes)
SDLOutput: silence started...
(0+) (AU #2) SDLOutput: silence ended (15360 bytes)
SDLOutput: silence started...
(5+) (AU #2) SDLOutput: silence ended (15360 bytes)
SDLOutput: silence started...

**Comment by andimik** [comment]
See https://github.com/JvanKatwijk/eti-stuff/issues/40
