### ISSUE TITLE
Sort console output by stream

### ISSUE THREAD

**Issue by andimik** [Opendigitalradio/dablin#23]
Currently the console prints the found services one after the other:

> SDLOutput: using SDL version '2.0.4'
> ETISource: reading from '/home/andreas/rte.eti'
> FICDecoder: found new audio service: SId 0x2245, subchannel  7, DAB
> FICDecoder: found new audio service: SId 0x2247, subchannel  6, DAB
> FICDecoder: found new audio service: SId 0x2248, subchannel  9, DAB
> FICDecoder: found new audio service: SId 0x2249, subchannel  8, DAB
> FICDecoder: found new audio service: SId 0x224A, subchannel 10, DAB
> FICDecoder: found new audio service: SId 0x2261, subchannel 12, DAB+
> FICDecoder: found new audio service: SId 0x2262, subchannel 13, DAB+
> FICDecoder: found new programme service label: SId 0x2262, 'RTE 2FM +'
> FICDecoder: found new audio service: SId 0x2201, subchannel  1, DAB
> FICDecoder: found new audio service: SId 0x2202, subchannel  2, DAB
> FICDecoder: found new audio service: SId 0x2203, subchannel  3, DAB
> FICDecoder: found new audio service: SId 0x2204, subchannel  4, DAB
> FICDecoder: found new programme service label: SId 0x2245, 'RTE 2XM'
> FICDecoder: found new programme service label: SId 0x2201, 'RTE Radio 1'
> FICDecoder: found new programme service label: SId 0x2248, 'RTE GOLD'
> FICDecoder: found new programme service label: SId 0x224A, 'RTE Radio 1Extra'
> FICDecoder: found new ensemble label: EId 0x2E01, 'DAB Ireland Mux1'
> FICDecoder: found new programme service label: SId 0x2261, 'RTE Radio 1 +'
> FICDecoder: found new programme service label: SId 0x2202, 'RTE 2FM'
> FICDecoder: found new programme service label: SId 0x2249, 'RTE PULSE'
> FICDecoder: found new programme service label: SId 0x2247, 'RTE Jr Radio'
> FICDecoder: found new programme service label: SId 0x2204, 'RTE RnaG'
> FICDecoder: found new programme service label: SId 0x2203, 'RTE LYRIC'

Why not sort this output (first line EID, then SID, then service label) or shorten the text, so that one could see immediately if there is anything new.

**Comment by basicmaster** [comment]
While in DVB there is a list of all services (the PAT), in DAB you just receive single service definitions - without knowing when you received all services. But this would be necessary to afterwards output a sorted list of all services in the ensemble. Hence currently all services are output just after they have been found (this way you also see when a new service starts). Despite that the output will soon change and only display one line per SId that combines subchannel and label, as the FIC handling is changed a bit.

The new DAB spec added a feature called "Configuration Information" (FIG 0/7) which allows to transmit the service count and therefore be able to tell when all services have been found. But it is currently not present by any ensemble I receive and will take time until it is used in the real world.

So I close this for now.
