### ISSUE TITLE
Link to ODR fdk has changed

### ISSUE THREAD

**Issue by andimik** [Opendigitalradio/dablin#25]
Grüß dich Stefan,

In https://github.com/Opendigitalradio/dablin#alternative-dab-decoder I guess you wanted to link to the opendigitalradio fdk package.

Seems it changed its path to https://github.com/Opendigitalradio/fdk-aac

**Comment by basicmaster** [comment]
Hallo Andreas,

you're right: After renaming some of the repos and separating the fdk-aac lib from ODR-AudioEnc some time ago, this link should have been adjusted. Thanks for reporting this!
