### ISSUE TITLE
feh.h not found

### ISSUE THREAD

**Issue by mistrey** [Opendigitalradio/dablin#3]
Make failed with message
"dabplus_decoder.h:41:17: schwerwiegender Fehler: fec.h: Datei oder Verzeichnis nicht gefunden"

**Comment by basicmaster** [comment]
Hmm, did you install the necessary [ka9q-fec](https://github.com/Opendigitalradio/ka9q-fec) lib?

**Comment by mistrey** [comment]
No. Thank you for the hint and sorry for the noise.
