### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by veso266** [Opendigitalradio/dablin#30]
Hi is it posible for someone to compile this for windows?

Thanks for Anwsering and Best Regards

**Comment by basicmaster** [comment]
I haven't tried yet to compile a Windows version but it should be possible somehow ;-)

**Comment by mpbraendli** [comment]
@basicmaster do you intend to support windows for dablin? If not, then this is not really an issue, but a wish.

**Comment by basicmaster** [comment]
@mpbraendli: The main platform is Linux, but it might be interesting to see whether a complation with e.g. MinGW works or not, or whether OS-depending modifications are required here. I will check.

**Comment by maceyldn** [comment]
Hi All,

I've rolled a non-gtk win32 version. See -> http://zippy.itrad.co.uk/dablin-win32.zip

I'll write up some instructions at some point.

Andy

**Comment by cyang812** [comment]
@maceyldn Thank you very much. But could you open your source?

**Comment by maceyldn** [comment]
No modifications to the Source Code. Just requires Cygwin and some packages.

I'll do a pull request, create a script that installs what you need and compiles it.

Andy

**Comment by cyang812** [comment]
@maceyldn
 Hi, I use your tool under win7. 
 It works and is really awesome.
 Could I read your source and script?

**Comment by basicmaster** [comment]
@maceyldn:
A MR with build script/how-to would be really appreciated. Depending on its length, it could be integrated into the existing README.

**Comment by k-otixxx** [comment]
@cyang812 
How to start dablin.exe with specific parameters?
I want to test eti-streams from Enigam2 receiver.
In Ubuntu works, but with freezes in sound.

**Comment by andimik** [comment]
The parameters are the same as under Linux

**Comment by cyang812** [comment]
@k-otixxx 
It's same as under Linux

**Comment by k-otixxx** [comment]
I see.
First cmd.exe and from command prompt write or must make some starting script.
Could you post some example, sorry for inconvinience.
Thanks!

**Comment by andimik** [comment]
You have to know the SID. dablin will only play one (!) SID, which you have specified.

dablin_gtk does not need it, as you have a GUI

**Comment by cyang812** [comment]
@k-otixxx 
OK. Here is my test command.
0xf203 is sid in my test eti file.

```
dablin.exe -s 0xf203 name.eti
```

**Comment by andimik** [comment]
But there are examples also in the readme...

**Comment by basicmaster** [comment]
I managed to compile DABlin on Windows with Cygwin myself. For this I had to apply some modifications to the code. I just added also some hints to the README.

(with Mingw/MSYS2 I unfortunately had no success so far, as `cmake` just hangs...)

@maceyldn:
Do you want to share further information to be added to the README?
I also wonder what you did about the AAC decoder, as your ZIP doesn't include a DLL for it. Did you statically link FAAD2 into the EXE file?

If there is nothing else, I will close this issue in some days...

**Comment by maceyldn** [comment]
Hey Guys, Sorry been really busy! Will pick this up over the weekend and tidy stuff up!

A

**Comment by k-otixxx** [comment]
Any chances for compiling for Android?

**Comment by basicmaster** [comment]
I currently have no plans for an Android version, but am of course open for any contributions ;-)

**Comment by maceyldn** [comment]
Guys,
Please see attached.
This is what i used to compile it.

[dablin-install.txt](https://github.com/Opendigitalradio/dablin/files/2299718/dablin-install.txt)

Let me know how you get on.

**Comment by maceyldn** [comment]
Gents,

Please see attached.
This is what i used to compile successfuly under Cygwin.

Any Questions/Obervations shout!
Give a go! :)

[dablin-install-notes.txt](https://github.com/Opendigitalradio/dablin/files/2299744/dablin-install-notes.txt)

**Comment by basicmaster** [comment]
Interesting notes, thanks!

As far as I can see, this `apt-cyg` tool installs the desired packages like Cygwin's `setup.exe` would do.

Indeed some question arise:

Why do you build all the libs yourself? Most of them are already available via Cygwin. FAAD2 isn't, so compiling makes sense (but it would be better to use the original source from www.audiocoding.com though). You also need only one of the two AAC decoder FDK-AAC and FAAD2. The latter one is the default.

I also wonder why you had to modify the CMake file to enable C++11, as the unmodified version worked for me some days ago.

Could you try if building works with your setup (without the custom build packages - except FAAD2) with the steps I recently added to the [README](https://github.com/Opendigitalradio/dablin/tree/next#windows-cygwin)? Note that you need to use the `next` branch.

**Comment by maceyldn** [comment]
Keine Problem!,

Yes apt-cyg is rather useful! especially for scripting installs in Cygwin!

I'll be honest, I built them because there's a guilty pleasure in compiling! :o)

I was compiling from the head before (forgot about the next branch sorry)  and was getting various issues around the file functions. ftello e.t.c. Google pointed to changing to C++11.

Just compiled the 'next' branch on my existing cygwin from before and it compiled first time.
I'll run up a new enviroment and try installing the packages and compile FAAD2. Will let you know.

**Comment by maceyldn** [comment]
@basicmaster Can you share me a DAB+ ETI? I have no way to test those...

**Comment by maceyldn** [comment]
Ok, so this appears to compile..

Can someone try it out?

[dablin-next.txt](https://github.com/Opendigitalradio/dablin/files/2299874/dablin-next.txt)

**Comment by basicmaster** [comment]
The mentioned file functions required the POSIX API level to be set correctly. Maybe the different C++11 parameter (C++11 had already been enabled from the very beginning) had the same effect.

I tend to avoid the usage of external dependencies as much as possible. As `setup.exe` allows to specifies packages on the cmdline, I will try this way to install the required packages for simple installation of the required packages. I will get back to you later.

> Can you share me a DAB+ ETI? I have no way to test those...

Assuming that you live [in London](https://www.ukwtv.de/cms/grossbritannien-dab/london-dab.html) or [the UK in general](https://www.ukwtv.de/cms/grossbritannien-dab.html), you should already be able to receive AAC services. The SDL National ensemble for example contains "Jazz FM Stereo", or the London trial on 9A contains many AAC services. They tend to sound quite horrible, but this is just due to low bitrate and usage of SBR+PS ;-)

**Comment by basicmaster** [comment]
Yes, there is still room for improvement in UK. In Germany the last MP2 service switched to AAC 1-2 years ago IIRC. However the Munich IRT Test ensemble (on 7A) sometimes still has a MP2 service on air.

Please find attached a short dump of Munich's local ensemble (11C): [2018-08-21.eti.zip](https://github.com/Opendigitalradio/dablin/files/2307368/2018-08-21.eti.zip)

**Comment by andimik** [comment]
Do I remember correctly Deutschlandradio was it?

**Comment by basicmaster** [comment]
It was DRadio's Deutschlandfunk (DLF) that switched to AAC on 01.06.2016.

**Comment by maceyldn** [comment]
Ah Charivari! My Favourite! 96.3 Gong ain't bad either! Thanks @basicmaster :)

**Comment by basicmaster** [comment]
> Ah Charivari! My Favourite! 96.3 Gong ain't bad either!

Hmm, these are two of the many stations that don't really differ between each other and have to repeat their station name after every song ;-)

OK, I tried the cmdline params for Cygwin's `setup.exe` and it is possible to pre-select packages for installation using `-P`, resulting for all libs in

```
setup-x86 -P git,make,cmake,gcc-core,gcc-g++,libmpg123-devel,libfdk-aac-devel,libSDL2-devel,libiconv-devel,libgtkmm3.0-devel,autoconf,automake,libtool
```

I just added this information to the README.
But I still wonder why you have to set `PKG_CONFIG_PATH`. I don't need that with my setup.

Besides that I guess that we can close this issue soon. :-)

**Comment by basicmaster** [comment]
OK, closing here.
