### ISSUE TITLE
Debian (and Ubuntu) package

### ISSUE THREAD

**Issue by alexmyczko** [Opendigitalradio/dablin#32]
Hi

I just found the RFP at https://bugs.debian.org/870808

and prepared a package at...
http://sid.ethz.ch/debian/dablin/

I guess it'll make it into Debian some day..

**Comment by alexmyczko** [comment]
http://cdn-fastly.deb.debian.org/debian/pool/main/d/dablin/

**Comment by russel** [comment]
Just as feedback: dablin Debian package seems to load fine on Debian Sid for me.

**Comment by basicmaster** [comment]
Thank you for packaging dablin. This will certainly lower the barrier for people that are not able to compile it themselves.

I tried to install the package on Ubuntu 16.04 but cannot fulfill the `libglibmm-2.4-1v5 (>= 2.54.0)' dependency. Seeing the quite long dependency in `control` I wonder whether the libs that libgtkmm-3.0 depends on could be removed, as the libgtkmm-3.0 packet itself already requires these dependencies, which should be enough.

To add a link to the README, would https://packages.debian.org/sid/dablin be suitable (currently I get a 500 error)?

**Comment by alexmyczko** [comment]
Nice

Have to check about the deps.

the link is good keep hammering reload it works sometimes better link:

http://packages.debian.org/dablin
same w ubuntu
packages.ubuntu.com/dablin
or the generic one using repology.org

i wasnt able to test it with my rtl sdr fitibit fc00012 chip though. any plan to support that? i saw it is already an issue but for welle.io, qt-dab same problem.

best,
alex

**Comment by andimik** [comment]
Which issue with the chip you are talking about?

**Comment by alexmyczko** [comment]
https://github.com/AlbrechtL/welle.io/issues/146

**Comment by alexmyczko** [comment]
sorry for the noise obviously I was missing dabtools
