### ISSUE TITLE
DRC process

### ISSUE THREAD

**Issue by cyang812** [Opendigitalradio/dablin#41]
Does this tools support dynamic range control?

**Comment by basicmaster** [comment]
DABlin doesn't have any DRC support itself.

For **MP2 services (DAB)**, DRC is a custom extension by DAB. As the audio decoder is not aware of it, too, there is no support at all here.

For **AAC services (DAB+)**, DRC is part of the AAC standard. Both FAAD and fdk-aac have DRC processing in their source code and seem to apply it - if DRC data is present (I don't know whether there are services that make use of it). I haven't checked the implications of this though...

Does this answer your question? Do you have a specific need for this?

**Comment by dabfree** [comment]
I think DRC is one of the features deprecated in V2.1.1 of the standard
anyway.

R.

**Comment by dabfree** [comment]
You're right!

There are references in there still so I must have just had a pleasant
dream. ;-D

R.

**Comment by dabfree** [comment]
It's not part of the minimum spec, that's all!

:-D

**Comment by basicmaster** [comment]
OK great, so I close here.
