### ISSUE TITLE
Adding -z switch to the linker flags breaks linking on macOS using clang.

### ISSUE THREAD

**Issue by npm-sdr** [Opendigitalradio/dablin#44]
Adding -z switch to the linker flags breaks linking on macOS using clang.

```
[ 66%] Linking CXX executable dablin_gtk
clang: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
ld: warning: option -s is obsolete and being ignored
ld: unknown option: -z
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

_Originally posted by @npm-sdr in https://github.com/Opendigitalradio/dablin/commit_comment/create#commitcomment-31847496_

**Comment by basicmaster** [comment]
(I slightly edited your comment to preserve the line breaks)

Could you please post the output of the `cmake` call? And could you put `VERBOSE=1` in front of your `make` call, and post the (affected) result lines here?

**Comment by npm-sdr** [comment]
Hi Stefan,

Please find attached the build log as requested.

Regards,
Niro.

[dablin_build_log.txt](https://github.com/Opendigitalradio/dablin/files/2729857/dablin_build_log.txt)

**Comment by basicmaster** [comment]
Hmm, I can't really reconstruct the situation here. Does the result change, if you apply the following patch? [linker_flags.patch.txt](https://github.com/Opendigitalradio/dablin/files/2753320/linker_flags.patch.txt)

**Comment by npm-sdr** [comment]
Hi Stefan,

I applied the patch and re-tried. It's still failing but with one less
warning. Passing the linker flags to the linker using -Wl made no
difference to -s and -z flags but the warning re unused -pie flag is now
gone.

ld: warning: option -s is obsolete and being ignored

ld: unknown option: -z

I suspect clang-10.0.0 on macOS 10.14.2 doesn't support -z anymore and -s
and flag is being deprecated.

$ clang --version

Apple LLVM version 10.0.0 (clang-1000.11.45.5)

Target: x86_64-apple-darwin18.2.0

Thread model: posix

InstalledDir:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Regards,
Niro.

**Comment by basicmaster** [comment]
Interesting that it makes a different in terms of PIE.....on my system GNU ld crashes with `-Wl,-pie`...the other changes are fine and lead to the same result.

> I suspect clang-10.0.0 on macOS 10.14.2 doesn't support -z anymore and -s and flag is being deprecated.

So the question arises, how are PIE, RELRO and striping enabled on Mac. Is there a different way? What does [checksec.sh](https://github.com/slimm609/checksec.sh) show, with the current compilation result on the one hand, and without the hardening added by problematic commit on the other hand?

**Comment by basicmaster** [comment]
As there currently seems no way to use the respective params with clang/LLVM, I disabled the recently added parameters for now, if clang is used. Please check if this fixes your compilation and if so, close this issue.

**Comment by npm-sdr** [comment]
Hi Stefan,

I've just updated to the top of next branch and rebuilt - builds fine on macOS now.

Sorry for the delay and many thanks.
Niro.

**Comment by npm-sdr** [comment]
Fixed

**Comment by barracuda156** [comment]
@npm-sdr These are not supported by GCC either. In fact, it is Apple linker does not accept these, compiler seems irrelevant.
