### ISSUE TITLE
RTL_TCP as source

### ISSUE THREAD

**Issue by jpuigs** [Opendigitalradio/dablin#51]
Would it be posible to have a command line option to play content from a RTL_TCP server ?

Usage: dablin_gtk [OPTIONS] [file]

  -R <<ip:port>>          Plays RTL_TCP signal from server at IP:Port

**Comment by andimik** [comment]
You can do it in combination with https://github.com/JvanKatwijk/eti-stuff

**Comment by basicmaster** [comment]
Adding such a feature would require that DABlin itself does the complete signal decoding from raw samples. This is however not the aim of DABlin (its processing starts on ETI level). Furthermore this is a quite complex task and already done quite well by other tools. Thus this is something that unfortunately will never be implemented in DABlin.

So you might want to use the mentioned `eti-cmdline`, which seems to have support for RTL_TCP (though the README doesn't list it at supported input devices). You then can use it together with DABlin with channel changing etc. as usual.

**Comment by jpuigs** [comment]
Ok, you're right, as I don't use DABlin with USB dongle, I forgot that it needs dab2eti or something like that.

I'll investigate eti-cmdline.
Thanks.
