### ISSUE TITLE
DABlin GTK Icons on macOS

### ISSUE THREAD

**Issue by npm-sdr** [Opendigitalradio/dablin#52]
Hi Stefan,

A long time ago you spotted that the icons were missing from macOS version of DABlin. I Just spent a bit of time this evening to get the icons working.

It turns out that installing gtkmm+3 doesn't install the icons. To get the icons, I had to install "adwaita-icon-theme" package (`brew install adwaita-icon-theme').

Can I update README.md with macOS instructions?

I've attached a screenshot of DABlin on macOS.

Regards,
Niro.

<img width="914" alt="Screenshot 2019-08-06 at 20 31 10" src="https://user-images.githubusercontent.com/33637299/62571412-2f978400-b889-11e9-97d9-a1c1b9b33eb6.png">

**Comment by basicmaster** [comment]
Hi Niro,

interesting that the icons are not available in the actual GTK package and require a separate package. How did you find out?

I wonder if this is a missing dependency in the package sources and whether it would therefore make sense to fix this on distribution/homebrew side. So also other affected tools using GTK would be fixed. Did you check that by chance?

Besides that it definitely makes sense to add a new subsection to the [compilation section](https://github.com/Opendigitalradio/dablin/tree/next#compilation) to also cover MacOS. Depending on whether there are many differences compared to the default (linux) case, it could make sense to just mention the differences or instead add step-by-step instructions for building. Please feel free to open a merge request on this.

**Comment by basicmaster** [comment]
As the Windows instructions come a bit later, I put the macOS instructions below them. I also made some minor changes (indent, typos). Thank you for your patch!
