### ISSUE TITLE
Show DL+ ?

### ISSUE THREAD

**Issue by mickaelmonsieur** [Opendigitalradio/dablin#54]
Hello,
Is it possible to display DL+ information?
Mickael

**Comment by basicmaster** [comment]
Hi Mickael,

this is something that definitely will be added, however it will take some time, until I can address this.

**Comment by mickaelmonsieur** [comment]
would it be possible to have at least the DL+ information in 'raw' format in the console if it is easier than in the GUI?

eg: 

```
##### parameters { #####
DL_PLUS=1
# this tags "Michael Jackson" as ITEM.ARTIST
DL_PLUS_TAG=4 5 14
# this tags "Thriller" as ITEM.TITLE
DL_PLUS_TAG=1 23 7
##### parameters } #####
Now: Michael Jackson - Thriller

```

**Comment by basicmaster** [comment]
This is not really easier than displaying the information in the GUI. Besides that, this is not the kind of information to be shown in the console, as it changes very regularly. So this information would prevent a user to see other more relevant changes, which are shown in the console as well.

**Comment by basicmaster** [comment]
With version 1.14.0, DL+ support is now available.
