### ISSUE TITLE
unsupported TAG item 'dlpt'

### ISSUE THREAD

**Issue by andimik** [Opendigitalradio/dablin#56]
Playing the EDI stream from IRT by using the following command

`wget -q -O - https://edistream.irt.de/services/3 | dablin_gtk -f edi -I -1`

will result in lots of these error messages

> EDIPlayer: ignored unsupported TAG item 'dlpt' (3776 bits)

**Comment by basicmaster** [comment]
The message results from data packets of custom IRT data related to the HRADIO project. It is allowed to transmit such custom data (like e.g. commercial DAB multiplexers do as well); it is just a bit annoying maybe. Is this something you would prefer to be hidden?

**Comment by andimik** [comment]
Well, as you cannot find anything about "dlpt" and this is not supported in dablin I would suggest to hide it and only display it together with an additional switch `-v` or `--verbose`.
