### ISSUE TITLE
Make subchannel data available in CLI

### ISSUE THREAD

**Issue by haditim** [Opendigitalradio/dablin#57]
Hi,
Thanks for the amazing work.

I use dablin cli for EDI decoding. However, I am wondering if that would be possible to make the same data that populates the GTK widgets also available in the CLI. For example the list of channels, programs, audio level and other statistic can be dumped to a json/yaml/toml file as it was done in [etisnoop](https://github.com/Opendigitalradio/etisnoop) and get updated every once in a while.
Please let me know if such a feature is already implemented or there is a possibility to add it.
Thanks

**Comment by basicmaster** [comment]
Hi,

DABlin is designed to be a playback application with some more detailled output sometimes, but its task is rather not to output information regularly and in a structured way. This is actually the task of analysers like etisnoop. AFAIK etisnoop currently only processes ETI, but I guess it would be welcomed if you want to add EDI input to it ;-)

**Comment by mpbraendli** [comment]
Sure it would be welcome!
I have a little test-tool inside http://git.mpb.li/git/odr-edilib/about/ which can analyse EDI and convert it to ETI. Maybe that can help you for your analysis needs.

**Comment by haditim** [comment]
Thanks a lot for swift replies.
I just though that since the GTK widgets are populated anyways, one could also make the data available relatively easily. If this is not the case then I'll be trying to use the test tool @mpbraendli mentioned.
Thanks again for the amazing project.
