### ISSUE TITLE
No Audio for HE-AACv2 in Ubuntu 20.04

### ISSUE THREAD

**Issue by andimik** [Opendigitalradio/dablin#62]
I've reinstalled my laptop with a clean installation of Ubuntu 20.04.

But I have OFTEN (not always) no sound at stations using HE-AACv2. All other (LC, v1, mono) work.

```
$ dpkg -l | grep faad
ii  libfaad-dev:amd64                          2.9.1-1                                    amd64        freeware Advanced Audio Decoder - development files
ii  libfaad2:amd64                             2.9.1-1                                    amd64        freeware Advanced Audio Decoder - runtime files
```

```
EnsemblePlayer: playing sub-channel 6 (DAB+)
EnsemblePlayer: format: HE-AAC v2, 48 kHz Stereo @ 48 kBit/s
AACDecoder: using decoder 'FAAD2'
SDLOutput: using audio buffer of 192000 bytes
SDLOutput: audio opened; driver name: pulseaudio, freq: 48000, channels: 2, size: 18432, samples: 2304, silence: 0x00, output: 32bit float
(AAC) (AAC) (AAC) (AAC) (AAC) (AAC) (AAC) (AAC) (AAC) (AAC) (AAC) (AAC) (AAC) (AAC) (AAC) (AAC) (AAC) (AAC) (AAC) (AAC) (AAC) (AAC) (AAC)
```

BTW: Same with Qt-DAB. All HE-AAC stations work, but when playing v2 there is the following error message (repeated each frame I guess):

> Warning: Unexpected channel configuration change

Maybe this helps to identify the issue.

**Comment by andimik** [comment]
I'm sorry, I was writing this issue for a longer time and did not know - at the same time - a similar issue was reported.

**Comment by basicmaster** [comment]
Thanks; I close this issue in favour of #61.

**Comment by jpuigs** [comment]
:laughing: 
Don't worry, it seems that both have seen that problem at the same time.

**Comment by andimik** [comment]
But I have no idea, why sometimes I have sound, and sometimes not.
