### ISSUE TITLE
Cannot play some services on DAB Italia

### ISSUE THREAD

**Issue by andimik** [Opendigitalradio/dablin#66]
A couple of days ago the mux DAB Italia has changed its configuration and now I am no more able to play these services:

- '* RDS *' ('* RDS *')
- 'Capital Funky' ('CapitalF')
- 'M DUE O DANCE' ('DANCE')
- 'Deejay 30 Songs' ('30 Songs')

```
$ cat /tmp/dabitalia.eti | ni2out --l
* DAB Italia * (0x5009)
 0 :             R101 (0x5215) Pri subch= 4 start=120 CUs= 36 PL=eep-3a bitrate=48 DAB+
 1 :          * RDS * (0x5264) Pri subch= 8 start=288 CUs= 36 PL=eep-3a bitrate=48 DAB+
 2 :          Capital (0x5219) Pri subch= 5 start=156 CUs= 48 PL=eep-3a bitrate=64 DAB+
 3 :          M DUE O (0x5233) Pri subch= 6 start=204 CUs= 48 PL=eep-3a bitrate=64 DAB+
 4 :          105 DAB (0x5286) Pri subch=11 start=324 CUs= 36 PL=eep-3a bitrate=48 DAB+
 5 :          Kc2Test (0x5288) Pri subch=13 start=456 CUs= 72 PL=eep-3a bitrate=96 DAB+
 6 :          Kc3Test (0x5289) Pri subch=14 start=528 CUs= 72 PL=eep-3a bitrate=96 DAB+
 7 :    Capital Funky (0x5285) Pri subch=17 start=672 CUs= 24 PL=eep-3a bitrate=32 DAB+
 8 :    M DUE O DANCE (0x5287) Pri subch=18 start=696 CUs= 24 PL=eep-3a bitrate=32 DAB+
 9 :      Radio 24 +1 (0x5282) Pri subch=19 start=720 CUs= 36 PL=eep-3a bitrate=48 DAB+
10 :  Deejay 30 Songs (0x5283) Pri subch=20 start=756 CUs= 24 PL=eep-3a bitrate=32 DAB+
11 :          RR News (0x5284) Pri subch=21 start=780 CUs= 36 PL=eep-3a bitrate=48 DAB+
12 :      Radio Maria (0x51cc) Pri subch= 1 start=  0 CUs= 36 PL=eep-3a bitrate=48 DAB+
13 :   Radio Radicale (0x5210) Pri subch= 2 start= 36 CUs= 36 PL=eep-3a bitrate=48 DAB+
14 :         Radio 24 (0x5245) Pri subch= 7 start=252 CUs= 36 PL=eep-3a bitrate=48 DAB+
15 :          Kc1Test (0x5280) Pri subch=12 start=360 CUs= 96 PL=eep-2a bitrate=96 DAB+
16 :         RMALB.IA (0x52cc) Pri subch=15 start=600 CUs= 36 PL=eep-3a bitrate=48 DAB+
17 :           Deejay (0x5214) Pri subch= 3 start= 72 CUs= 48 PL=eep-3a bitrate=64 DAB+
18 :    * RDS * Relax (0x5281) Pri subch=16 start=636 CUs= 36 PL=eep-3a bitrate=48 DAB+

```

They stop after around one second and the console only shows `(AAC) (AAC) (AAC) (AAC) (AAC) (AAC)` inserted by a time stamp like `0:00:02` continuously ...

Attached see eti-file recorded from 9 East today. 

[dabitalia.zip](https://github.com/Opendigitalradio/dablin/files/6017729/dabitalia.zip)

Remark: EuroDAB on the same transponder has no problems.

**Comment by basicmaster** [comment]
Hmm, I'm able to play all the services in the ETI dump. Is this maybe related to #62/#61? Is "RR News" affected, too?

**Comment by andimik** [comment]
Shame on me, I really forgot about that.

Yes, this was the solution, thanks. I thought it already has been fixed after such long time.

I just realized the in the Readme there is one dependency for libtool missing:

`sudo apt-get install libtool`

Will send a PR.

PS. Sorry, have not tested RR News.

**Comment by andimik** [comment]
Remark: EuroDABItalia has lots of v2 services, but as far as I remember I could hear all of them ...
