### ISSUE TITLE
Console Version Output Error rate and/or reception strength?

### ISSUE THREAD

**Issue by 4920441** [Opendigitalradio/dablin#72]
Hi,

is it possible to output the error rate and reception strength on the console as well?

I search for a solution to plot the signal strength over a longer time period of one channel, but didn't find anything appropriate yet.

Thanks a lot !

Cheers

4920441

**Comment by andimik** [comment]
Hi, what is your input source?

If eti-cmdline, then I have a solution with gnuplot, which I have not published yet.

**Comment by 4920441** [comment]
It's a RTL_SDR Device.  So should be possible, I think.

**Comment by andimik** [comment]
It will look like that.

![1610833050766blob](https://github.com/Opendigitalradio/dablin/assets/24510556/be225c8a-a1c1-4016-b77f-9d8ea742c17d)

**Comment by 4920441** [comment]
Looks  fine.   I'd like it to pipe it into my influxdb instead of gnuplot, but  if it outputs some kind of ascii  that shouldnot be any problem to do so.

**Comment by andimik** [comment]
Then it's easy. Just extract the values from the eti-cmdline output to your tool.

In my case I am writing eti files for about 5 mins when I am abroad (on holiday) and analyze them at home. The gnuplot helps me to use the best recorded file.

**Comment by andimik** [comment]
Yes, looks like that.

[DAB-9C_2020-08-14T20h22m43Z_9C.log.txt](https://github.com/Opendigitalradio/dablin/files/11653825/DAB-9C_2020-08-14T20h22m43Z_9C.log.txt)

**Comment by basicmaster** [comment]
This affected the received signal before it reaches DABlin, therefore I close here.
