### ISSUE TITLE
Missing package in Ubuntu in README.md

### ISSUE THREAD

**Issue by andimik** [Opendigitalradio/dablin#75]
https://github.com/Opendigitalradio/dablin/blob/17b06d6b8f2981ea8867fece094b5d3267b8e8c1/README.md?plain=1#L58

A fresh new Ubuntu has no `cmake` and `git` installed. It makes sense to mention them there as well.

**Comment by basicmaster** [comment]
Git and CMake are already mentioned some lines earlier, in the "General" section:
https://github.com/Opendigitalradio/dablin/blob/17b06d6b8f2981ea8867fece094b5d3267b8e8c1/README.md?plain=1#L31

**Comment by andimik** [comment]
Oh, you are right.
