### ISSUE TITLE
libfaad not in Fedora Rawhide

### ISSUE THREAD

**Issue by russel** [Opendigitalradio/dablin#8]
It appears that libfaad is not packaged by Fedora. Instructions for building DABlin on Fedora will need to include instructions on building this.

**Comment by russel** [comment]
This can be solved by adding RPMFusion to the list of package repositories for dnf and installing the faad2-devel package.

**Comment by mpbraendli** [comment]
Can you create a pull request that describes in the README what to install in Fedora?

**Comment by russel** [comment]
Yes I can. It may be a day or two, as I need to put my notes into shape and just run through it all again to make sure it is right.

**Comment by basicmaster** [comment]
OK, interesting....looking forward to your PR!

**Comment by russel** [comment]
Initial amendments to README.md created as a pull request. I am assuming people should not merge their own pull requests, except in exceptional circumstances.

@basicmaster Will you be pushing your changes to DABtools as a pull request to the newly created repository? If so this README will need to change a bit more.

**Comment by russel** [comment]
This issue is now effectively closed since the "workaround" is now known and documented.

**Comment by basicmaster** [comment]
> Initial amendments to README.md created as a pull request. I am assuming people should not merge their own pull requests, except in exceptional circumstances.
Thanks for your PR. Absolutely; this is the best way in that case.

> @basicmaster Will you be pushing your changes to DABtools as a pull request to the newly created repository? If so this README will need to change a bit more.
Yes, I did some moments ago. I will then adopt the README accordingly.

**Comment by basicmaster** [comment]
README updated by d0de55a.
