### ISSUE TITLE
DABtools fork?

### ISSUE THREAD

**Issue by russel** [Opendigitalradio/dablin#9]
DABlin effectively requires DABtools. The DABTools repository at https://github.com/linuxstb/dabtools appears to be abandoned. There are issues and pull requests not dealt with. This seems it is time for a fork. Might it be appropriate for Opendigitalradio to fork the project and pick up the pull requests (one of which is for a CMake build for example)?

**Comment by mpbraendli** [comment]
On principle you are absolutely right. What holds us back is the lack of time.

I see that @elgroj has done quite a few changes to the code in november, and @basicmaster has also done some changes: https://github.com/linuxstb/dabtools/network

I would welcome if somebody would agree to take care of that project, and if we find a maintainer we can also accept the project into ODR.

**Comment by russel** [comment]
I am intending to get back to working on Me TV (https://github.com/Me-TV/Me-TV), doing a rewrite of the dvbsrc plugin in GStreamer Bad Plugins, and possibly adding a dabsrc plugin if that is a good thing to do. I had more or less decided not to add DAB to Me TV but to create a separate UI, but then found DABlin which is effectively the UI I would have written (well it needs a Gtk3 makover I think). I will thus in all likelihood start contributing to DABlin.

dab2etl is code that clearly forms the basis (ideas if not actual code) of a librtlsdr-based dabsrc plugin (and there is the idea of using the /dev/swradio0 device where appropriate. So I think I will be involved in the code in a way that I am happy to volunteer to be the maintainer of a DABTools repository.

**Comment by mpbraendli** [comment]
Ok excellent, keep us updated! The official discussion channel of ODR is the crc-mmbtools google groups as described on the bottom of http://www.opendigitalradio.org/ so it would be beneficial to post a small announcement there.

**Comment by russel** [comment]
I have joined and will post summarising the state. linuxstb has explicitly agreed to a change earlier today, it just remains to make formal arrangements.

**Comment by basicmaster** [comment]
Indeed DABlin needs dabtools to be a complete DAB receiver. So it would be great to have everything together in ODR.

**Comment by russel** [comment]
I believe that what needs to happen is for someone with ODR powers to accept the dabtools from @linuxstb I am then happy to be a member of the team that maintains the dabtools repository on behalf of ODR.

**Comment by mpbraendli** [comment]
https://github.com/Opendigitalradio/dabtools
And you should have received an invite for the group, with push rights to dablin and dabtools.
